export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'

export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'
