export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'
export const FETCH_REPOSITORIES_FAIL = 'FETCH_REPOSITORIES_FAIL'

export const FETCH_REPOSITORY = 'FETCH_REPOSITORY'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'

export const CREATE_REPOSITORY = 'CREATE_REPOSITORY'
export const DELETE_REPOSITORY = 'DELETE_REPOSITORY'
