export const FETCH_REPOSITORIES_START = 'FETCH_REPOSITORIES_START'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'

export const CREATE_REPOSITORY_START = 'ADD_REPOSITORY_START'
export const CREATE_REPOSITORY_SUCCESS = 'ADD_REPOSITORY_SUCCESS'
export const CREATE_REPOSITORY_FAIL = 'ADD_REPOSITORY_FAIL'

export const FETCH_REPOSITORY_START = 'FETCH_REPOSITORY_START'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'
export const FETCH_REPOSITORY_FAIL = 'FETCH_REPOSITORY_FAIL'
