export const START_OPERATION = 'START_OPERATION'
export const FAIL_OPERATION = 'FAIL_OPERATION'

export const CREATE_REPOSITORY = 'CREATE_REPOSITORY'
export const DELETE_REPOSITORY = 'DELETE_REPOSITORY'

export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'

export const FETCH_REPOSITORY = 'FETCH_REPOSITORY'
export const FETCH_REPOSITORY_SUCCESS = 'FETCH_REPOSITORY_SUCCESS'

